### ISSUE TITLE
[BLIP-9] Repo Branch Standards

### ISSUE THREAD

**Issue by humbitious** [eea-oasis/baseline-blips#11]
# Branch Naming Standards

There should be prominently featured in the docs and top readme what our community's standards are for Branch naming and management (included hygiene).

---
Copyright
Copyright and related rights waived via CC0-Universal.

(This template adapted from the EIP template at https://github.com/ethereum/EIPs/

**Comment by GoldenBit0** [comment]
Notes from 11/15/21 Core Devs session:

- Core Devs should comment under issue with proposals for branch naming standards.

**Comment by skarred14** [comment]
Agreed, this can be addressed ideally by using a plugin like `husky` to add custom branch naming rules.

**Comment by ognjenkurtic** [comment]
**Branch naming and git flow proposal:**

_master_ - main development branch, feature and release branches branched from it, changes only through the PR process.

_feature/this-is-a-new-feature-branch_ - in case no related BLIP exists
_feature/BLIP-9-repo-branch-standards_ - in case related BLIP exists

_release/1.0.0_ - cut from master when ready

We can introduce more complex git flow once we have more development activity.

**Rebase instead of merge:**

After completed work on a feature branch, rebase master before opening a PR. After PR approved rebase again to make sure changes from latest master picked up before merging the PR into master.

**Commit messages proposal:**

In the commit message, always continue the sentence "This commit does ...". Examples of good commit messages:
 "Rename examples folder in the root of the repo to reference-implementations" 
 "Add RabbitMQ client as another messaging interface implementation"
 "Bump dependency packages versions to fix potential security issues"


Let me know your thoughs.

**Comment by GoldenBit0** [comment]
Notes from 11/29/21: 

- Unanimous approval for @ognjenkurtic's proposal above
- @humbitious & @GoldenBit0 will update docs and readme

**Comment by humbitious** [comment]
Propose that this change can wait until after we consider and move on new BLIP #12, switching from "master" to "main", because, whether we choose to make the master/main change or not, if we make BLIP-9's changes to readme/docs before then, we may have to change again.  #conservationOfMotion  @Therecanbeonlyone1969 ?

**Comment by GoldenBit0** [comment]
12/13/21 Core Devs:

- Change once we have relative URIs in place

**Comment by GoldenBit0** [comment]
1/10/22 Core Devs:

Kyle Suggestions: 
- Features have branch name feat/name
- Bugs have bugfix/name
- Blips/#

Next steps:
- @humbitious will write docs

**Comment by ognjenkurtic** [comment]
In addition to my proposal above, full list of naming conventions with included comments:

master(main after BLIP-12) - main development branch, feature and release branches branched from it, changes only through the PR process.

feature/this-is-a-new-feature-branch - in case no related BLIP exists
feature/BLIP-9-repo-branch-standards - in case related BLIP exists

bugfix/name-of-the-bug

release/1.0.0 - cut from main when ready

**Comment by GoldenBit0** [comment]
1/24/22 Core Devs:

- Ognjen will update docs

**Comment by ognjenkurtic** [comment]
Opened a [PR](https://github.com/eea-oasis/baseline/pull/457) while waiting for @sonalllpatelll for update regarding proper way to update the docs.

**Comment by Kasshern** [comment]
@ognjenkurtic  Once the docs have been reconciled following a synchronization issue due to the gitbook's branch pointer and the main branch, all doc changes will go through PRs to main. Expecting that reconciliation to be done this week.

**Comment by GoldenBit0** [comment]
5/2/22 Core Devs Call:
- Docs change will be pushed before next core devs call.

**Comment by GoldenBit0** [comment]
6/13/22 Core Devs Call:

- Pending PR for doc change, will be complete this week.

**Comment by GoldenBit0** [comment]
6/27/22 Core Devs Call:

- Docs updated, work can proceed

**Comment by GoldenBit0** [comment]
7/11/22 Core Devs Call:

- In progress

**Comment by GoldenBit0** [comment]
7/25/22 Core Devs Call:

- @ognjenkurtic please provide an update when ready or let us know if someone can help.

**Comment by ognjenkurtic** [comment]
Wrapping this up on Thursday, no help needed.

**Comment by ognjenkurtic** [comment]
https://github.com/eea-oasis/baseline/pull/490

**Comment by ognjenkurtic** [comment]
PR is merged. Is there anything else needed or we close this one?

**Comment by GoldenBit0** [comment]
We should be good. Thanks @ognjenkurtic!
