### ISSUE TITLE
[BLIP-11] Master to Main

### ISSUE THREAD

**Issue by humbitious** [eea-oasis/baseline-blips#12]
# Master to Main Proposal

Proposed: rename the baseline github repos legacy "master" branches to current standard of "main."  Here is a good article on doing it fast and right: https://www.r-bloggers.com/2020/07/5-steps-to-change-github-default-branch-from-master-to-main/

Acceptance criteria:

- [ ] Main is the primary branch after change
- [ ] No code breaks due to rename process
- [ ] No documentation or known references to the repos have pointers to "master" or where they used to require "master" they now contain "main".

John Wolpert @humbitious 

---
Copyright
Copyright and related rights waived via CC0-Universal.

(This template adapted from the EIP template at https://github.com/ethereum/EIPs/

**Comment by GoldenBit0** [comment]
12/13/21 Core Devs Session:

- Provide & Unibright teams should review if change will cause issues prior to 1/10/22

**Comment by GoldenBit0** [comment]
1/10/22 Core Devs Session:

- Kyle: change shouldn't cause any breaks
- Next steps: Sonal to connect with Oasis to conduct next steps

**Comment by GoldenBit0** [comment]
Renamed as BLIP-11 since work is in progress.

**Comment by GoldenBit0** [comment]
1/10/22: Sonal contacted Oasis to align on who will be working on action.

**Comment by claurau** [comment]
@humbitious @GoldenBit0 I'd like to go ahead and make this change. In order to do that I need to know the following. 

I would like to adjust the following repos. Please let me know if this list is right:

- eea-oasis/baseline: migrate to main
- eea-oasis/baseline-roadmap: migrate to main
- eea-oasis/baseline-website: migrate to main
- eea-oasis/baseline-standard: migration to main already done
- eea-oasis/baseline-grants: migration to main already done
- eea-oasis/baseline-outreach: migration to main already done
- eea-oasis/baseline-blips: migration to main already done

I would like to follow current official github recommendations for renaming master to main. They are documented here: https://github.com/github/renaming#renaming-existing-branches. This is now a single click, with the consequences outlined there. Please confirm that this is acceptable.

Some notes on each repo.

# eea-oasis/baseline

This repository has a lot of users. They will all need to switch from master to main. They will be notified as described in the renaming instructions I referenced above. I will migrate this using the single click rename described above.

# eea-oasis/baseline-roadmap

Less users, but the same as above. I will migrate this using the single click rename described above.

# eea-oasis/baseline-website

This one is a bit different, because it is a website which gets deployed to Netlify. I will migrate this using the single click rename described above. After renaming, there will need to be a secondary step where the Netlify configuration is checked, and if it deploys from master, then this will need to be updated to point to main. 

Please let me know if this  is all correct so that I can go ahead and make these changes.

**Comment by GoldenBit0** [comment]
@claurau 

One comment - we have archived the baseline-roadmap repo, so no need to rename it. 

The rest looks good to me

**Comment by claurau** [comment]
@GoldenBit0 I assume that this a GO from you, then. Will do the update today.

**Comment by claurau** [comment]
Done for /baseline

![Screenshot 2022-01-27 at 10 35 38](https://user-images.githubusercontent.com/4882728/151332212-7f6d5aee-29da-4364-97ad-eaf35cd67fe4.png)

**Comment by claurau** [comment]
Done for /baseline-website.

@GoldenBit0 @humbitious please review and close if everything is okay.

**Comment by GoldenBit0** [comment]
Reviewed.
BLIP complete.
